### ISSUE TITLE
Compatibility with the 7th edition

### ISSUE THREAD

**Issue by MarcelHWachter** [JustinMShea/wooldridge#5]
Hi,

is this package compatible with the 7th edition of the book?

**Comment by JustinMShea** [comment]
Yes. For context, the update from the 5th to the 6th edition was minimal, adding just 6 more data sets, bringing the total number of data sets from 105 to 111. In updating to the 7th, I do not believe any additional data sets were added. I did reach out to the publisher during the text books pre-production on this matter, and they were unaware of any additional data sets at that time. However, if more did get added, we can add them here as well, and update the documentation accordingly.

**Comment by mrclwchtr** [comment]
That's great. 
Thanks for the fast reply.

**Comment by JustinMShea** [comment]
Sure, glad I could help. You caught me at the desk, before 25 other alerts buried yours :) 

And thanks for your query, I'll do a little more digging and make updates if needed.

**Comment by VolodymyrVakhitov** [comment]
Hi Justin,

Cengage holds a book companion site: https://www.cengage.com/cgi-wadsworth/course_products_wp.pl?fid=M20b&product_isbn_issn=9781337558860

They have several versions of the data sets, for some reason. Apparently, the one in Stata is the fullest, it has 115 files, whereas the one in R, for example, has only 111 files. The one in Excel has only 108 files, but as a plus, they have descriptions for each of the data files. 

In particular, the file JTRAIN98, which is used in a newly added section 3.7 in the 7th edition is missing. I believe the other four files are used in some new computer assignments or newly added sections and would be quite useful too. 

Anyway, could you, please, use the Stata version of the data (http://academic.cengage.com/resource_uploads/downloads/1337558869_635109.zip) and update the Wooldridge package, please? It's really a bomb for teaching! 

Thanks a million! 

Best wishes,
Volodymyr

**Comment by JustinMShea** [comment]
Thanks Volodymyr,

I left the issue open hoping someone else might look into this, so your comments and work here are most appreciated!


Indeed, the wooldridge package does use the Stata files as it's source, not the R files. These were several good reasons for this,  and it appears Stata files are Jeffrey Wooldridge's storage medium of choice. The R, excel, and other files appear to be more sparsely maintained by graduate students and have other issues besides being incomplete in number. Due to this, I wrote .R scripts to convert the Stata files to RData files, so I should be able to add these over the upcoming U.S. holidays.

Other than the ease of loading data, a key feature of the package is the included documentation for each data set. The textbook doesn't always fully describe the data set one is working on, so I find this context very helpful for students. For jtrain, just type `?jtrain` in the console and the R Documentation file will launch with all information documented in t he Wooldridge Data Set Handbook.  Fortunately, I was able to locate the 7th edition Data Set Handbook under the instructor section of the Cengage site. Including it will also help partially solve issue #3 , which has been open for awhile.

Thanks again and I'm glad you find the package useful,
Justin

**Comment by calciferanalytics** [comment]
Hi Justin, thank you first of all for maintaining this package, it makes it easier to teach Econometrics using R. The `JTRAIN98` dataset that VolodymyrVakhitov is referring to is not the same as the `train` dataset, so `?train` is of no help. Unfortunately, the "JTRAIN98" dataset is only in STATA format. I solved the issue for myself by importing the JTRAIN98.dta stata file (from VolodymyrVakhitov's link) to R using the **haven** package and then write.csv() to save it as a csv file.  I hope it's helpful.

**Comment by JustinMShea** [comment]
@calciferanalytics Hi Aram,
Thank you, I'm glad you find the package useful. Yes, I am aware the jtrain set is not what @VolodymyrVakhitov was referencing and that the full data set for the 7th edition is in Stata format. Having working with Stata data to upgrade from the 5th to the 6th edition, I updated the scripts for the 7th. Your can read them here if interested see data-raw/data-cleaning-7th.R

I've preferred to use the `readstata13` package, which is a much more stable, faster, and consistent package than `haven`, so I would recommend giving it a try if you load Stata files often!

Justin

**Comment by JustinMShea** [comment]
Thank you for bringing this to my attention @MarcelHWachter and thank you @VolodymyrVakhitov, for doing a little leg work to make this update a bit less time consuming! This will work right away:

`remotes::install_github("JustinMShea/wooldridge")`

I will likely wait to fully tackle issue #3 before pushing the update to CRAN, but that should be soon.

Thanks again,
Justin
